es:
  host: 120.79.176.54
#  host: 47.107.153.61
#  host: 58.210.179.70
  port: 9200
  scheme: http
  # 单位ms
  socket_timeout: 60000
  # 单位ms
  connect_timeout: 60000
  # 单位ms
  search_timeout: 2000
  # 返回文档的最低评分
  min_score: 0.5
  # ElasticSearch的用户名密码
  username: elastic
  password: elastic
#  password: xinluo@123
  # 搜索时使用的分词算法
  search_analyzer: ik_smart
  # 原索引名称
  index_name: original
  # 索引别名，用于实际搜索时使用
  alias_name: original_alias
  # 重建索引时使用的索引名称
  temp_index_name: original_dest
  # 默认的索引属性配置文件
  properties_json: /json/index_properties.json
  # 全字段检索的字段列表
  all_fields: admission_dep,admission_ward,attending_physician,auxiliary_examination,birthplace,chief_complaint,chief_physician,daily_disease_course,examination_data,family_history,first_disease_course,marriage_history,past_medical_history,operation_record,personal_history,physical_examination,present_illness_history

logging:
  file:
    path: ./logs/
